# Generated by Django 2.0.7 on 2018-08-27 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='software',
            options={'verbose_name_plural': 'Software'},
        ),
        migrations.RenameField(
            model_name='software',
            old_name='date_posted',
            new_name='datePosted',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='team',
            new_name='title',
        ),
    ]
