# Generated by Django 2.0.7 on 2018-08-29 17:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_auto_20180827_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RenameField(
            model_name='software',
            old_name='body',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='software',
            name='datePosted',
        ),
        migrations.AddField(
            model_name='software',
            name='dateModified',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='software',
            name='dateSubmitted',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='link',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software.Software'),
        ),
    ]
