# Generated by Django 2.0.7 on 2018-08-29 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0004_auto_20180829_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='iGemTeamName',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='software',
            name='iGemYear',
            field=models.IntegerField(default=2018),
        ),
    ]
