# Generated by Django 2.0.7 on 2018-08-29 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0005_auto_20180829_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='software',
            old_name='iGemTeamName',
            new_name='iGem_team_name',
        ),
    ]
