# Generated by Django 2.0.7 on 2018-08-29 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0008_auto_20180829_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='software',
            options={'verbose_name_plural': 'Software'},
        ),
    ]
