# Generated by Django 2.0.7 on 2018-08-30 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0009_auto_20180829_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='software',
        ),
        migrations.AddField(
            model_name='software',
            name='link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
