# Generated by Django 2.0.7 on 2018-08-30 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0010_auto_20180830_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='software',
            name='link',
        ),
        migrations.AddField(
            model_name='link',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software.Software'),
        ),
    ]
