# Generated by Django 2.0.7 on 2018-08-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0011_auto_20180830_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='software',
        ),
        migrations.AddField(
            model_name='software',
            name='link',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
