# Generated by Django 2.0.7 on 2018-08-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0012_auto_20180830_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='iGemTeamName',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='software',
            name='iGemYear',
            field=models.IntegerField(blank=True, default=2018),
        ),
    ]
