# Generated by Django 2.0.7 on 2018-08-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0013_auto_20180830_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='iGemTeamName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='iGemYear',
            field=models.IntegerField(default=2018),
        ),
    ]
