# Generated by Django 2.0.7 on 2018-08-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0014_auto_20180830_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='iGemTeamName',
            field=models.CharField(blank=True, default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='software',
            name='iGemYear',
            field=models.IntegerField(blank=True, default=2018, null=True),
        ),
    ]
