# Generated by Django 2.0.7 on 2018-08-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0016_auto_20180830_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='iGemYear',
            field=models.CharField(blank=True, default=0, max_length=4),
            preserve_default=False,
        ),
    ]
