# Generated by Django 2.1.1 on 2018-09-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
