# Generated by Django 2.1.1 on 2018-09-30 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_auto_20180930_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='dateModified',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='software',
            name='dateSubmitted',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='software',
            name='iGemTeamName',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='software',
            name='iGemYear',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
