# Generated by Django 2.1.1 on 2018-09-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0003_auto_20180930_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='link',
            field=models.URLField(),
        ),
    ]
