# Generated by Django 2.1.1 on 2018-10-06 17:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0004_auto_20180930_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='description',
            field=ckeditor.fields.RichTextField(default='Hello'),
            preserve_default=False,
        ),
    ]
